---
config:
    theme: neutral
---

flowchart TB
  subgraph Users
    internet_user["Internet user"]
  end
  subgraph Frontends
    webfrontend["WebFrontEnd"]
  end
  subgraph Backends
    api_backend["API backend"]
    catalogservice["CatalogService"]
    commandservice["CommandService"]
    ordering_service["Ordering Service"]
  end
  subgraph Data Storage
    mydb["MyDB"]
  end
  subgraph External Systems
    payment_service["Payment Service"]
  end


BAD

End user browses the product catalog
internet_user ->> webfrontend: Browse catalog
webfrontend ->> api_backend: GET /catalog
api_backend ->> catalog_service: fetchProducts()
catalog_service ->> mydb_storage: SELECT products
mydb_storage -->> catalog_service: products[]
catalog_service -->> api_backend: products[]
api_backend -->> webfrontend: 200 OK
webfrontend -->> internet_user: Display catalog

GOOD

End user browses the product catalog
internet_user ->> webfrontend: Browse catalog
webfrontend ->> api_backend: GET /catalog
api_backend ->> catalogservice: fetchProducts()
catalogservice ->> mydb: SELECT products
mydb -->> catalogservice: products[]
catalogservice -->> api_backend: products[]
api_backend -->> webfrontend: 200 OK
webfrontend -->> internet_user: Display catalog